### ISSUE TITLE
Training problem ?

### ISSUE THREAD

**Issue by yeyewen** [jspan/PHYSICS_SR#2]
@jspan I placed the data as you mentioned, But 
![image](https://user-images.githubusercontent.com/37136363/80211608-99023180-8668-11ea-9880-db4a18801dcd.png)
I changed the directory as the error guidance.Then 
![image](https://user-images.githubusercontent.com/37136363/80211870-0e6e0200-8669-11ea-976f-cacfa5ed464f.png)
I download the model that you trained
`cd code
python main.py --dir_data <your root> --data_test DIV2K --model physics_sr --scale 2 --save physics_sr_x2 --save_results`
![image](https://user-images.githubusercontent.com/37136363/80212262-bdaad900-8669-11ea-8667-9dfbf69e960d.png)
I think your readme of this code providing a test code, How do I train your model？

**Comment by jspan** [comment]
your trainset should place data like this:
![image](https://user-images.githubusercontent.com/37973116/80972496-c0b77d80-8e50-11ea-9ea2-f325073f98a1.png)
and then modify the command with --dir data , not --data_test
it is different with the testset, so you have the erro:  No Such file or directory

**Comment by yeyewen** [comment]
@jspan I am sure that the data were placed as you said。
this is my command. But it still go to evaultion without training.
`python main.py --dir_data ../datasets/DIV2Kself --data_test Set5  --model physics_sr --scale 2 --save physics_sr_x2 --save_results
`
![image](https://user-images.githubusercontent.com/37136363/81269433-e1afe680-907b-11ea-834c-ea4417b5d2b6.png)

![image](https://user-images.githubusercontent.com/37136363/81269095-6ea67000-907b-11ea-89ec-2141bcb313cd.png)
and my  another colleague  also got the same problem.
Thanks！

**Comment by yeyewen** [comment]
@jspan the main.py set test_only=True ,  I set test_only=False . It worked
